# SPDX-FileCopyrightText: 2023 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

# Config  Reference: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      jsonwebtoken:
        patterns:
          - "io.jsonwebtoken:*"
    ignore:
      # Ignore major version updates to spring-boot-starter-parent
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.cloud:spring-cloud-dependencies"
        update-types: ["version-update:semver-major"]
